language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
- pip install .
script: iwebrepl --help
deploy:
  provider: pypi
  user: __token__
  password:
    secure: CrAJpdX8j7crkJA+NvYK8YNgvOktDDKeUM+231hUUAFKziTmHAQ6/379tJac0FWPWs5PGNDKI/m0V3Ve0ENXdPRj2vhjxKGk7oakqItN0F3QdsT5aXvB4af2+IhqfsEIOQV/4jr1lXA26nUocJpObxcXuYgGR1mYAi8RBxGRBMsfwNjgLsRBKzwgd7j5A3BlpRJOnZoSF1DQgB/nyvWyGyCQpv0EUf9MtEtCjMnNHMgjX8oQVtr7XC3z6l0x0eBmwcxHeEOQbJ1wGWDZB+7uILSyCBfMyh0HucXWViH8izWuINfQXHQqgC9tE/BFXBtij0yxTrFy2+dAzrZ1nYLO8npCbrUj7NsFuHW+KASoGYDDclmjtqBVoK4dKwByTZez9MEUpkhJQwX+lx5Z5/dOWNzwZEjrudFJuT1AO4vqIsaFhChakHPSN7sEp55+ENtGIdMV8cwqbfepJ6l7kfPRYDUshU/tlaVMsPeZ24I0OoMi7RrvnORfhpv4bas0fuHnGt+NVfhxaooPKexfR+ZwegAKF+7RYsyHDqpfM2ZAJflX7azPipS3aR+oo4ByaKUHDzAIWNmHQZSjlWMPGITYRTWJbzoH6HD0mRVWcvQHMT5P1YctyGrMgwdjtcJkfuNkN0sbHXuyDmzKm3Ye1ceyWgNr8rcrocIugwii0gIoAr4=
  skip_existing: true
  on:
    tags: true
